imports:
    - { resource: parameters.yml }

services:
    gn36.hookup.functions.hookup:
        class: gn36\hookup\functions\hookup
        arguments:
            - @dbal.conn
            - %tables.gn36.hookup.members%
            - %tables.gn36.hookup.dates%
            - %tables.gn36.hookup.available%
    gn36.hookup.events.posting:
        class: gn36\hookup\event\posting
        arguments:
            - @gn36.hookup.functions.hookup
            - @template
            - @dbal.conn
            - @user
            - @auth
            - @request
        tags:
            - { name: event.listener }
    gn36.hookup.events.viewtopic:
        class: gn36\hookup\event\viewtopic
        arguments:
            - @gn36.hookup.functions.hookup
            - @template
            - @dbal.conn
            - @user
            - @auth
            - @request
            - %core.root_path%
            - %core.php_ext%
            - %gn36.hookup.path%
        tags:
            - { name: event.listener }
    gn36.hookup.cron.weekly_reset:
        class: gn36\hookup\cron\weekly_reset
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @log
            - @gn36.hookup.functions.hookup
            - %core.root_path%
            - %core.php_ext%
            - %tables.gn36.hookup.dates%
            - %gn36.hookup.reset.run_interval%
        calls:
            - [set_name, [gn36.hookup.cron.weekly_reset]]
        tags:
            - { name: cron.task }
